# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            Tarak's Page
email:            halbkarat@gmail.com
description:      Tarak's persönliche Page
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site
twitter_username: halbkarat
github_username:  tarak

# Build settings
markdown:         kramdown
theme:            minima
gems:             [bootstrap, autoprefixer-rails, jekyll-assets, jekyll-paginate]
sass:
  sass_dir:       _sass
  style:          compressed
paginate:         5
paginate_path:    '/blog/page:num'
permalink:        pretty

# About/contact
author:
  name:           Tarak
  description:    A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar:       3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  usernames:
    linkedin:     https://www.linkedin.com/in/lizhihao
    github:       https://github.com/tarak
    # facebook:   <hide>
    twitter:      https://twitter.com/Li_Zhihao
    weibo:        http://weibo.com/41173780
    email:        http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags:     '/blog/tags/' }
  Github Projects:
    - 'https://github.com/tarak'

# Where are tags and categories displayed
tag_page:         '/blog/tags/'
category_page:    '/blog/categories/'
