# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            Tarak's GitHub Page
email:            halbkarat@gmail.com
description:      Tarak's persönliche Page auf GitHub
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site
twitter_username: halbkarat
github_username:  tarak

exclude: ['README.md']

# Build settings
markdown:         kramdown
highlighter: rouge
theme:            minima
gems:             [jekyll-sitemap, jekyll-seo-tag, jekyll-feed, jekyll-assets, jekyll-paginate]
sass:
  sass_dir:       _sass
  style:          compressed
paginate:         5
paginate_path:    '/blog/page:num'
permalink:        pretty

# About/contact
author:
  name:           Tarak
  description:    A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar:       aafa4d1850e29c79aba059ecf5285ec7
  usernames:
    github:       https://github.com/tarak

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags:     '/blog/tags/' }
  Github Projects:
    - 'https://github.com/tarak'

# Where are tags and categories displayed
tag_page:         '/blog/tags/'
category_page:    '/blog/categories/'
